# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  gpg-key:
    description: 'GPG key file to use'
    required: true
  gpg-passphrase:
    description: 'GPG key to use'
    required: true
  input-path:
    description: 'Path to work on'
    required: true    
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context
    GPG_KEY_VAR: ${{ inputs.gpg-key }}
    INPUT_PATH_VAR: ${{ inputs.input-path }}
  args:
    - ${{ inputs.gpg-passphrase }}
