# action.yml
name: 'gpg-sign-action'
author: Stephan Fuhrmann
description: 'GPG sign files with detached ASCII signature'
inputs:
  gpg-key:
    description: 'GPG key file to use as a textual PGP PRIVATE KEY BLOCK'
    required: true
  gpg-passphrase:
    description: 'GPG key unlocking passphrase'
    required: true
  path:
    description: 'Path to work on'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context
    GPG_KEY_VAR: ${{ inputs.gpg-key }}
    INPUT_PATH_VAR: ${{ inputs.path }}
  args:
    - ${{ inputs.gpg-passphrase }}
