name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      GPG_KEY_VAR: ${{ secrets.GPG_KEYFILE }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PUBKEY: ${{ vars.GPG_PUBKEY }}
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gpg-sign-action

   
    - name: Test with right passphrase
      run: |
        mkdir -p github/workspace/testdir
        echo "hello" > github/workspace/testdir/testfile
        docker run -v$(pwd)/github:/github -eGPG_KEY_VAR -eINPUT_PATH_VAR=testdir  gpg-sign-action "${GPG_PASSPHRASE}"

        echo "GPG version:"
        gpg --version

        echo "Importing pubkey"
        echo "${GPG_PUBKEY}" | gpg --import

        echo "Directory listing"
        ls -alR github/workspace

        echo "Verifying signature"
        gpg --verify github/workspace/testdir/testfile.asc

    - name: Test with wrong passphrase
      run: |
        rm -fr github
        mkdir -p github/workspace/testdir
        echo "hello" > github/workspace/testdir/testfile
        set +e
        docker run -v$(pwd)/github:/github -eGPG_KEY_VAR -eINPUT_PATH_VAR=testdir  gpg-sign-action "THISISNOTYOURPASSPHRASE"
        RETURNCODE=$?
        set +e
        if [ "$RETURNCODE" -eq 0 ]; then
          echo "❌ Error: Docker run was successful, but should have failed"
          exit 1
        else
          echo "✅ Docker run failed as expected (Returncode $RETURNCODE)"
        fi

    - name: Test with wrong key
      run: |
        rm -fr github
        mkdir -p github/workspace/testdir
        echo "hello" > github/workspace/testdir/testfile
        set +e
        docker run -v$(pwd)/github:/github -eGPG_KEY_VAR=foobar -eINPUT_PATH_VAR=testdir  gpg-sign-action "THISISNOTYOURPASSPHRASE"
        RETURNCODE=$?
        set +e
        if [ "$RETURNCODE" -eq 0 ]; then
          echo "❌ Error: Docker run was successful, but should have failed"
          exit 1
        else
          echo "✅ Docker run failed as expected (Returncode $RETURNCODE)"
        fi
  